// app/dummyData/dummymateriildata.ts
import { MaterilGroup } from "@/app/component/materiltable";

export const dummyMaterilData: MaterilGroup[] = [
  {
    romawi: "I",
    title: "BMN MATKOMLEK SATKOMLEK TNI",
    items: [
      // 1. Block Up Converter (BUC) C-Band
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "15",
        kel: "4",
        subKel: "1",
        subSubKel: "5",
        jenis: "1",
        tipe: "1",
        urut: "1",
        name: "Block Up Converter (BUC) C-Band",
        merkType: "NJT5762N",
        serialNumbers: ["NJT5762N"],
        negaraPembuat: "Jepang",
        tahunPembuatan: "2018",
        tahunPemakaian: "2019",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "0",
        rb: "1",
        persen: "0",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 2. Block Up Converter (BUC) Codan (unit 1)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "15",
        kel: "4",
        subKel: "1",
        subSubKel: "5",
        jenis: "1",
        tipe: "1",
        urut: "2",
        name: "Block Up Converter (BUC) Codan",
        merkType: "Codan",
        serialNumbers: ["COD12345"],
        negaraPembuat: "Australia",
        tahunPembuatan: "2019",
        tahunPemakaian: "2020",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "0",
        rb: "1",
        persen: "0",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 3. Block Up Converter (BUC) Codan (unit 2)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "15",
        kel: "4",
        subKel: "1",
        subSubKel: "5",
        jenis: "1",
        tipe: "1",
        urut: "3",
        name: "Block Up Converter (BUC) Codan",
        merkType: "Codan",
        serialNumbers: ["COD67890"],
        negaraPembuat: "Australia",
        tahunPembuatan: "2019",
        tahunPemakaian: "2020",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "0",
        rb: "1",
        persen: "0",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 4. Bird RF Wattmeter
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "15",
        kel: "4",
        subKel: "1",
        subSubKel: "5",
        jenis: "1",
        tipe: "1",
        urut: "4",
        name: "Bird RF Wattmeter",
        merkType: "Bird",
        serialNumbers: ["BRD001"],
        negaraPembuat: "USA",
        tahunPembuatan: "2017",
        tahunPemakaian: "2018",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "1",
        rr: "0",
        rb: "0",
        persen: "100",
        keterangan: "Peralatan Jaringan",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 5. Modem Satelit CDM570 AL (5 unit contoh)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "4",
        jenis: "1",
        tipe: "1",
        urut: "5",
        name: "Modem Satelit CDM570 AL",
        merkType: "Comtech",
        serialNumbers: ["CDM001", "CDM002", "CDM003", "CDM004", "CDM005"],
        negaraPembuat: "USA",
        tahunPembuatan: "2020",
        tahunPemakaian: "2021",
        jumlah: 5,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "50",
        keterangan: "Modem satelit kelas berat untuk jaringan telekomunikasi",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 6. Modem Satelit CDM600 AL (4 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "4",
        jenis: "1",
        tipe: "1",
        urut: "6",
        name: "Modem Satelit CDM600 AL",
        merkType: "Comtech",
        serialNumbers: ["CDM601", "CDM602", "CDM603", "CDM604"],
        negaraPembuat: "USA",
        tahunPembuatan: "2019",
        tahunPemakaian: "2020",
        jumlah: 4,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "50",
        keterangan: "Modem satelit kelas berat",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 7. Modem Spacenet (2 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "4",
        jenis: "1",
        tipe: "1",
        urut: "7",
        name: "Modem Spacenet",
        merkType: "Spacenet",
        serialNumbers: ["SPC01", "SPC02"],
        negaraPembuat: "USA",
        tahunPembuatan: "2018",
        tahunPemakaian: "2019",
        jumlah: 2,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "50",
        keterangan: "Perangkat keras jaringan satelit VSAT",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 8. Wireless PCI Card
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "22",
        jenis: "1",
        tipe: "1",
        urut: "8",
        name: "Wireless PCI Card G Desktop Adapter Airplus G",
        merkType: "D-Link",
        serialNumbers: ["DRCC37400392"],
        negaraPembuat: "Taiwan",
        tahunPembuatan: "2017",
        tahunPemakaian: "2018",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "75",
        keterangan: "Wireless G Desktop Adapter",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 9. Wireless Access Point
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "23",
        jenis: "1",
        tipe: "1",
        urut: "9",
        name: "Wireless Access Point",
        merkType: "D-Link",
        serialNumbers: ["WAP001"],
        negaraPembuat: "Taiwan",
        tahunPembuatan: "2017",
        tahunPemakaian: "2018",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "75",
        keterangan: "Titik akses nirkabel",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 10. Multimeter Uni-T (6 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "3",
        kel: "3",
        subKel: "1",
        subSubKel: "32",
        jenis: "1",
        tipe: "1",
        urut: "10",
        name: "Multimeter Uni-T",
        merkType: "UNI-T",
        serialNumbers: [
          "C173996468",
          "C181224707",
          "C181224700",
          "C181224701",
          "C173996477",
          "C17396477",
        ],
        negaraPembuat: "China",
        tahunPembuatan: "2020",
        tahunPemakaian: "2021",
        jumlah: 6,
        satuan: "Unit",
        kondisiB: "1",
        rr: "0",
        rb: "0",
        persen: "100",
        keterangan: "Alat Ukur Universal",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 11. Telephone (PABX) Panasonic (16 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "6",
        kel: "2",
        subKel: "1",
        subSubKel: "1",
        jenis: "1",
        tipe: "1",
        urut: "11",
        name: "Telephone (PABX)",
        merkType: "Panasonic",
        serialNumbers: [
          "8AAKB002352",
          "8AAKB002486",
          "8AAKB002366",
          "8AAKB002422",
          "8AAKB002457",
          "8AAKB002360",
          "8AAKB002351",
          "8AAKB002435",
          "8AAKB003146",
          "8AAKB002399",
          "8AAKB002474",
          "8AAKB002357",
          "8AAKB002411",
          "8AAKB002433",
          "8AAKB002476",
          "8AAKB002410",
        ],
        negaraPembuat: "Jepang",
        tahunPembuatan: "2016",
        tahunPemakaian: "2017",
        jumlah: 16,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "75",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 12. Laptop Notebook Axioo (4 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "1",
        subKel: "2",
        subSubKel: "3",
        jenis: "1",
        tipe: "1",
        urut: "12",
        name: "Laptop Notebook",
        merkType: "Axioo",
        serialNumbers: [
          "NKW217CUQDC2F01429",
          "NKW217CUQDC2F05953",
          "NKW217CUQDC2F00888",
          "NKW217CUQDC2F01465",
        ],
        negaraPembuat: "Indonesia",
        tahunPembuatan: "2021",
        tahunPemakaian: "2022",
        jumlah: 4,
        satuan: "Unit",
        kondisiB: "0",
        rr: "0",
        rb: "1",
        persen: "25",
        keterangan: "Personal Computer (PC)",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 13. Hub Switch GrandStream (4 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "10",
        kel: "2",
        subKel: "4",
        subSubKel: "3",
        jenis: "1",
        tipe: "1",
        urut: "13",
        name: "Hub Switch",
        merkType: "GrandStream",
        serialNumbers: [
          "21AVUK79H21ACFEF4",
          "21AVUK79H51B91968",
          "21AVUK79H21ACFFAO",
          "21AVUK79H21ACFFAA",
        ],
        negaraPembuat: "USA",
        tahunPembuatan: "2019",
        tahunPemakaian: "2020",
        jumlah: 4,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "60",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 14. CCTV
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "5",
        kel: "1",
        subKel: "5",
        subSubKel: "7",
        jenis: "1",
        tipe: "1",
        urut: "14",
        name: "CCTV (Camera Control Television System)",
        merkType: "HIK Vision",
        serialNumbers: ["162154837"],
        negaraPembuat: "China",
        tahunPembuatan: "2018",
        tahunPemakaian: "2019",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "70",
        keterangan: "Alat Kantor Lainnya",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 15. LCD Projector
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "5",
        kel: "1",
        subKel: "5",
        subSubKel: "48",
        jenis: "1",
        tipe: "1",
        urut: "15",
        name: "LCD Projektor/Infocus",
        merkType: "View Sonic",
        serialNumbers: ["000MD5316A079"],
        negaraPembuat: "Taiwan",
        tahunPembuatan: "2017",
        tahunPemakaian: "2018",
        jumlah: 1,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "60",
        keterangan: "",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 16. Quad Video Processor Server AV (2 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "6",
        kel: "1",
        subKel: "2",
        subSubKel: "24",
        jenis: "1",
        tipe: "1",
        urut: "16",
        name: "Quad Video Processor Server AV",
        merkType: "Vivotek",
        serialNumbers: ["-", "-"],
        negaraPembuat: "China",
        tahunPembuatan: "2019",
        tahunPemakaian: "2020",
        jumlah: 2,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "65",
        keterangan: "Peralatan Studio Video dan Film",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
      // 17. Antena UHF Stationary TV (5 unit)
      {
        bag: "1",
        unsr: "3",
        bid: "1",
        subBid: "4",
        subSubBid: "9",
        gol: "3",
        bidKlasifikasi: "6",
        kel: "3",
        subKel: "9",
        subSubKel: "3",
        jenis: "1",
        tipe: "1",
        urut: "17",
        name: "Antena UHF Stationary TV",
        merkType: "Starcom",
        serialNumbers: [
          "I120861901219",
          "I120861901217",
          "I120861901218",
          "I120861901216",
          "I120861901116",
        ],
        negaraPembuat: "China",
        tahunPembuatan: "2020",
        tahunPemakaian: "2021",
        jumlah: 5,
        satuan: "Unit",
        kondisiB: "0",
        rr: "1",
        rb: "0",
        persen: "75",
        keterangan: "Peralatan Antena UHF",
        gambar: "",
        updateTanggal: "2025-01-15",
        konseptor: "Admin",
      },
    ],
  },
];

export default dummyMaterilData;